keboola_get_stat_extractor_homepage:
    path: '/hello/{name}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Default:index'
keboola_getstat_extractor_configs_list:
    pattern: /configs
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:get'
    requirements:
        _method: GET
keboola_getstat_extractor_configs_add:
    pattern: /configs
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:post'
    requirements:
        _method: POST
keboola_getstat_extractor_configs_delete:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:delete'
    requirements:
        _method: DELETE
keboola_getstat_extractor_configs_getconfig:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:getConfig'
    requirements:
        _method: GET
keboola_getstat_extractor_configs_addrow:
    pattern: '/configs/{id}/rows'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_getstat_extractor_configs_addrowid:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_getstat_extractor_configs_getrow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:getRow'
    requirements:
        _method: GET
keboola_getstat_extractor_configs_deleterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:deleteRow'
    requirements:
        _method: DELETE
keboola_getstat_extractor_configs_updaterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:addRow'
    requirements:
        _method: PUT
keboola_getstat_extractor_configs_addcreds:
    pattern: '/configs/{id}/credentials'
    defaults:
        _controller: 'KeboolaGetStatExtractorBundle:Configs:addAttrs'
    requirements:
        _method: POST
